services:
  - type: web
    name: Angular-21-Auth-Boilerplate
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist/angular-21-auth-boilerplate/browser
    routes:
      - type: rewrite
        source: /*
        destination: /index.html